/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    JsonForm: typeof import('./../components/JsonForm.vue')['default']
    TAutoComplete: typeof import('tdesign-vue-next')['AutoComplete']
    TCascader: typeof import('tdesign-vue-next')['Cascader']
    TCheckboxGroup: typeof import('tdesign-vue-next')['CheckboxGroup']
    TColorPicker: typeof import('tdesign-vue-next')['ColorPicker']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TOption: typeof import('tdesign-vue-next')['Option']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
  }
}
